### ISSUE TITLE
Person: Gender has wrong type

### ISSUE THREAD

**Issue by jzych** [gitmajo/UniversityDatabase#16]
According to [Checklist](https://github.com/coders-school/Kurs-CPP/blob/master/L04-stl-containers/checklist.md) Gender should be an enum (or float if you asked me ;)

https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Person.hpp#L11

**Comment by gitmajo** [comment]
Thank you. ;)
