### ISSUE TITLE
Code style: Indetens

### ISSUE THREAD

**Issue by jzych** [gitmajo/UniversityDatabase#18]
Code inside {} brackets should have indent

https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Database.cpp#L14-L16
https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Database.cpp#L28-L30
https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Database.cpp#L42-L45
https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Database.cpp#L67-L81
https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Database.cpp#L88-L90
https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Database.cpp#L96-L98
https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Database.cpp#L104-L101

**Comment by gitmajo** [comment]
I don't know why it is not set in default vim indent style, manually solved. ;)
