### ISSUE TITLE
Code style: Unconsisten {} brackets style

### ISSUE THREAD

**Issue by jzych** [gitmajo/UniversityDatabase#19]
Code uses two different code styles for opening {} brackets

https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Database.cpp#L146-L152
https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/Database.cpp#L174-L181

**Comment by gitmajo** [comment]
Thanks, done.
