### ISSUE TITLE
PersonalID: CheckDay needs additional conditions

### ISSUE THREAD

**Issue by jzych** [gitmajo/UniversityDatabase#21]
What about months which have 30 day? And what about February which has 28 or 29 day depending if it's leap year? Right now date 31.04 or 30.02 is valid.

https://github.com/gitmajo/UniversityDatabase/blob/3aeff1f184441f3f75b2dfcd198ec518e83301b1/PersonalID.cpp#L66-L73

**Comment by gitmajo** [comment]
@jzych @LordLukin @majkel84 
I changed name of the function to better present my idea. 
I am using that function only to verify if yy-mm-dd was not changed to dd--mm-yy. 
That case is described on wiki as drawback of checking algorithm.
